//! Compiles the protobuf contract into Rust and bakes build provenance into
//! the binary. The Swift half of the same contract is generated by
//! `mise run generate:proto` through buf; Rust generates here instead so a
//! `cargo build` in a fresh clone never depends on buf being installed.

use std::path::PathBuf;

const PROTO_ROOT: &str = "../../proto";
const SERVICE_PROTOS: &[&str] = &[
    "../../proto/ond/v1/account_service.proto",
    "../../proto/ond/v1/assistant_service.proto",
    "../../proto/ond/v1/entitlement_service.proto",
    "../../proto/ond/v1/journey_service.proto",
    "../../proto/ond/v1/profile_service.proto",
    "../../proto/ond/v1/technique_service.proto",
    "../../proto/ond/v1/user_technique_service.proto",
];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);

    tonic_prost_build::configure()
        // Emitted so tonic-reflection can serve the schema, which is what makes
        // `grpcurl` work against a running server without a local copy of the
        // .proto files.
        .file_descriptor_set_path(out_dir.join("ond_v1_descriptor.bin"))
        .compile_protos(SERVICE_PROTOS, &[PROTO_ROOT])?;

    // The whole directory, not just the files above: adding a .proto must
    // trigger a rebuild even though it is not yet listed.
    println!("cargo:rerun-if-changed={PROTO_ROOT}");

    println!("cargo:rerun-if-env-changed=BUILD_GIT_COMMIT_HASH");
    println!(
        "cargo:rustc-env=BUILD_GIT_COMMIT_HASH={}",
        git_commit_hash()
    );
    println!(
        "cargo:rustc-env=BUILD_TIMESTAMP={}",
        chrono::Utc::now().to_rfc3339()
    );

    Ok(())
}

/// The commit this binary was built from, or `"unknown"` when nothing can
/// answer — a tarball build is normal, not a failure. `BUILD_GIT_COMMIT_HASH`
/// wins over git because `.dockerignore` excludes `.git`, so `deploy:api`
/// passes it as a build arg; without it `ond_build_info` is labelled
/// `"unknown"` in production, the one place the question is worth asking.
fn git_commit_hash() -> String {
    std::env::var("BUILD_GIT_COMMIT_HASH")
        .ok()
        .filter(|hash| !hash.trim().is_empty())
        .or_else(|| {
            std::process::Command::new("git")
                .args(["rev-parse", "--short", "HEAD"])
                .output()
                .ok()
                .filter(|output| output.status.success())
                .and_then(|output| String::from_utf8(output.stdout).ok())
        })
        .map_or_else(|| "unknown".to_owned(), |hash| hash.trim().to_owned())
}
